[package]
name = "limestone"
description = "Generate short-lived unique program derive address signers"
version = "0.1.0"
edition = "2021"
readme = "README.md"
license = "Apache-2.0"
authors = ["nifty-oss maintainers <maintainers@nifty-oss.org>"]
repository = "https://github.com/nifty-oss/limestone"

[dependencies]
solana-program = "^1.16"
